services:
  backend:
    container_name: biolink-backend
    build: 
      context: ./biolink-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./biolink-backend/.env
    restart: unless-stopped

  frontend:
    container_name: biolink-frontend
    build: 
      context: ./biolink-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend
    restart: unless-stopped